#!/bin/bash

jupyter nbextension     install --sys-prefix --py fileupload
jupyter nbextension     enable  --sys-prefix --py fileupload
jupyter nbextension     enable  --sys-prefix --py nglview
jupyter nbextension     enable  --sys-prefix --py appmode
jupyter serverextension enable  --sys-prefix --py appmode
